-- DATAPATH AUTOGENERATED USING gen_datapath.py

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.MyTypes.all;

entity cpu_datapath is
    generic (
        memory_defaults: mem(127 downto 0) := (others => x"00000000")
    );
    port (

        clock: in std_logic;

        -- alu;
        alu_shift_op : in word;
        alu_op : in word;
        alu_flags_in : in flags_t;
        alu_opcode : in DP_opcode_t;
        alu_ans : out word;
        alu_flags_out : out flags_t;

        -- regfile;
        regfile_r_addr_1 : in nibble;
        regfile_r_addr_2 : in nibble;
        regfile_w_addr : in nibble;
        regfile_data_in : in word;
        regfile_w_en : in std_logic;
        regfile_out_1 : out word;
        regfile_out_2 : out word;

        -- memory;
        memory_addr : in word;
        memory_data_in : in word;
        memory_w_en : in nibble;
        memory_data_out : out word;

        -- pmconnect;
        pmconnect_Rout : in word;
        pmconnect_Rin : out word;
        pmconnect_dt_opcode : in DT_opcode_t;
        pmconnect_enable : in std_logic;
        pmconnect_adr : in bit_pair;
        pmconnect_Min : out word;
        pmconnect_Mout : in word;
        pmconnect_MW : out nibble;

        -- shifter;
        shifter_shifter_in : in word;
        shifter_shifter_out : out word;
        shifter_carry_in : in std_logic;
        shifter_carry_out : out std_logic;
        shifter_shift_type : in bit_pair;
        shifter_shift_amt : in byte;

        -- predicator;
        predicator_condition : in condition_t;
        predicator_flags_in : in flags_t;
        predicator_p : out std_logic;

        -- instr_decoder;
        instr_decoder_instruction : in word;
        instr_decoder_instruction_class : out instruction_t;
        instr_decoder_DP_opcode : out DP_opcode_t;
        instr_decoder_condition : out condition_t;
        instr_decoder_DT_opcode : out DT_opcode_t;
        instr_decoder_shift : out shift_t
    );
end cpu_datapath;

architecture cpu_datapath_arc of cpu_datapath is
begin

    alu: entity work.alu port map (alu_shift_op, alu_op, alu_flags_in, alu_opcode, alu_ans, alu_flags_out);
    regfile: entity work.regfile port map (regfile_r_addr_1, regfile_r_addr_2, regfile_w_addr, regfile_data_in, regfile_w_en, clock, regfile_out_1, regfile_out_2);
    memory: entity work.memory generic map (memory_defaults) port map (clock, memory_addr, memory_data_in, memory_w_en, memory_data_out);
    pmconnect: entity work.pmconnect port map (pmconnect_Rout, pmconnect_Rin, pmconnect_dt_opcode, pmconnect_enable, pmconnect_adr, pmconnect_Min, pmconnect_Mout, pmconnect_MW);
    shifter: entity work.shifter port map (shifter_shifter_in, shifter_shifter_out, shifter_carry_in, shifter_carry_out, shifter_shift_type, shifter_shift_amt);
    predicator: entity work.predicator port map (predicator_condition, predicator_flags_in, predicator_p);
    instr_decoder: entity work.instr_decoder port map (instr_decoder_instruction, instr_decoder_instruction_class, instr_decoder_DP_opcode, instr_decoder_condition, instr_decoder_DT_opcode, instr_decoder_shift);

end cpu_datapath_arc;