-- TESTCASE AUTOGENERATED by gentest
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.MyTypes.all;

entity cpu_tb is
end cpu_tb;

architecture cpu_tb_arc of cpu_tb is
    signal clock: std_logic := '0';
    constant clock_period: time := 0.5 ns;
    signal input_data: word;
    signal memory: mem(127 downto 0) := (
        0 => X"E3A0EC01",
        1 => X"E6000011",
        2 => X"EA000000",
        3 => X"00000000",
        4 => X"E3A0000C",
        5 => X"E5900000",
        6 => X"E6000011",
        64 => X"E3A02000",
        65 => X"EF000000",
        66 => X"E1A01420",
        67 => X"E3510001",
        68 => X"1AFFFFFB",
        69 => X"E2822001",
        70 => X"EAFFFFF9",
        others => X"00000000" );
begin
    uut: entity work.cpu generic map (memory) port map (clock, input_data);

    clock <= not clock after clock_period/2;
    update_input: process
    begin
        wait for 5*clock_period;
        input_data <= x"000001AD";
        wait for 80*clock_period;
        input_data <= x"000000AD";
        wait for 50*clock_period;
        input_data <= x"000001AD";
    end process update_input;

end cpu_tb_arc;
