-- TESTCASE AUTOGENERATED by gentest
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.MyTypes.all;

entity cpu_tb is
end cpu_tb;

architecture cpu_tb_arc of cpu_tb is
    signal clock: std_logic := '0';
    constant clock_period: time := 2 ns;
    signal memory: mem(127 downto 0) := (
        0 => X"E3A00001",
        1 => X"E3A01000",
        2 => X"E3A02000",
        3 => X"E3A03006",
        4 => X"E3A04001",
        5 => X"E1530004",
        6 => X"0A000007",
        7 => X"E1A01000",
        8 => X"E1A02004",
        9 => X"E3520001",
        10 => X"C0800001",
        11 => X"C2422001",
        12 => X"CAFFFFFB",
        13 => X"E2844001",
        14 => X"EAFFFFF5",
        others => X"00000000" );
begin
    uut: entity work.cpu generic map (memory) port map (clock);

    clock <= not clock after clock_period/2;

end cpu_tb_arc;
