-- TESTCASE AUTOGENERATED by gentest
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.MyTypes.all;

entity cpu_tb is
end cpu_tb;

architecture cpu_tb_arc of cpu_tb is
    signal clock: std_logic := '0';
    constant clock_period: time := 2 ns;
    signal memory: mem(127 downto 0) := (
        0 => X"E3A00000",
        1 => X"E3A01001",
        2 => X"E1E0F000",
        3 => X"E0012000",
        4 => X"E3A00001",
        5 => X"E0012000",
        6 => X"E20F20FD",
        7 => X"E0212000",
        8 => X"E3A00000",
        9 => X"E0212000",
        10 => X"E3A01005",
        11 => X"E3A00014",
        12 => X"E0402001",
        13 => X"E0602001",
        14 => X"E0802001",
        15 => X"E08FF001",
        16 => X"E0A12000",
        17 => X"E0C12000",
        18 => X"E0612000",
        19 => X"E3A00000",
        20 => X"E3A01000",
        21 => X"E1100001",
        22 => X"E1300001",
        23 => X"E3500000",
        24 => X"E3500001",
        25 => X"E1500001",
        26 => X"E3A01001",
        27 => X"E1812000",
        28 => X"E1CF2001",
        others => X"00000000" );
begin
    uut: entity work.cpu generic map (memory) port map (clock);

    clock <= not clock after clock_period/2;

end cpu_tb_arc;
