-- TESTCASE AUTOGENERATED by gentest
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.MyTypes.all;

entity cpu_tb is
end cpu_tb;

architecture cpu_tb_arc of cpu_tb is
    signal clock: std_logic := '0';
    constant clock_period: time := 2 ns;
    signal memory: mem(127 downto 0) := (
        0 => X"E3A00060",
        1 => X"E3A010AD",
        2 => X"E3811CDE",
        3 => X"E38118FE",
        4 => X"E38114CA",
        5 => X"E3A02004",
        6 => X"E5A01004",
        7 => X"E7A01002",
        8 => X"E7201082",
        9 => X"E280000C",
        10 => X"E4801004",
        11 => X"E6801082",
        others => X"00000000" );
begin
    uut: entity work.cpu generic map (memory) port map (clock);

    clock <= not clock after clock_period/2;

end cpu_tb_arc;
